/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package deu.view;

import lombok.Getter;
import lombok.Setter;

import javax.swing.event.AncestorListener;
import java.awt.event.ActionListener;

/**
 *
 * @author oxxultus
 */
@Getter
@Setter
public class UserManagement extends javax.swing.JPanel {

    /**
     * Creates new form UserManagemenet
     */
    public UserManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profilePanel = new deu.view.custom.PanelRound();
        profileImageField = new deu.view.custom.LabelRound();
        profileNumberField = new deu.view.custom.TextFieldRound();
        profileNameField = new deu.view.custom.TextFieldRound();
        profileMajorField = new deu.view.custom.TextFieldRound();
        editProfileDataPanel = new deu.view.custom.PanelRound();
        editFieldTitlePanel = new deu.view.custom.PanelRound();
        editFieldTitle = new javax.swing.JLabel();
        numberLabel = new javax.swing.JLabel();
        editProfileNumberField = new deu.view.custom.TextFieldRound();
        nameLabel = new javax.swing.JLabel();
        editProfileNameField = new deu.view.custom.TextFieldRound();
        majorLabel = new javax.swing.JLabel();
        editProfileMajorField = new deu.view.custom.TextFieldRound();
        passwordLabel = new javax.swing.JLabel();
        editProfilePasswordField = new deu.view.custom.TextFieldRound();
        updateButton = new deu.view.custom.ButtonRound();
        deleteButton = new deu.view.custom.ButtonRound();
        userManagementPanel = new deu.view.custom.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1100, 550));
        setMinimumSize(new java.awt.Dimension(1100, 550));
        setLayout(null);

        profilePanel.setBackground(new java.awt.Color(20, 90, 170));
        profilePanel.setRoundBottomLeft(15);
        profilePanel.setRoundBottomRight(15);
        profilePanel.setRoundTopLeft(15);
        profilePanel.setRoundTopRight(15);
        profilePanel.setLayout(null);

        profileImageField.setBackground(new java.awt.Color(51, 51, 51));
        profileImageField.setForeground(new java.awt.Color(60, 63, 65));
        profileImageField.setRoundBottomLeft(30);
        profileImageField.setRoundBottomRight(30);
        profileImageField.setRoundTopLeft(30);
        profileImageField.setRoundTopRight(30);
        profilePanel.add(profileImageField);
        profileImageField.setBounds(10, 10, 115, 95);

        profileNumberField.setEditable(false);
        profileNumberField.setBackground(new java.awt.Color(255, 255, 255));
        profileNumberField.setForeground(new java.awt.Color(0, 0, 0));
        profileNumberField.setRound(10);
        profilePanel.add(profileNumberField);
        profileNumberField.setBounds(140, 30, 110, 27);

        profileNameField.setEditable(false);
        profileNameField.setBackground(new java.awt.Color(255, 255, 255));
        profileNameField.setForeground(new java.awt.Color(0, 0, 0));
        profileNameField.setRound(10);
        profilePanel.add(profileNameField);
        profileNameField.setBounds(140, 70, 110, 27);

        profileMajorField.setEditable(false);
        profileMajorField.setBackground(new java.awt.Color(255, 255, 255));
        profileMajorField.setForeground(new java.awt.Color(0, 0, 0));
        profileMajorField.setRound(10);
        profilePanel.add(profileMajorField);
        profileMajorField.setBounds(10, 115, 240, 27);

        add(profilePanel);
        profilePanel.setBounds(6, 6, 260, 160);

        editProfileDataPanel.setBackground(new java.awt.Color(20, 90, 170));
        editProfileDataPanel.setRoundBottomLeft(15);
        editProfileDataPanel.setRoundBottomRight(15);
        editProfileDataPanel.setRoundTopLeft(15);
        editProfileDataPanel.setRoundTopRight(15);
        editProfileDataPanel.setLayout(null);

        editFieldTitlePanel.setRoundBottomLeft(10);
        editFieldTitlePanel.setRoundBottomRight(10);
        editFieldTitlePanel.setRoundTopLeft(10);
        editFieldTitlePanel.setRoundTopRight(10);

        editFieldTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editFieldTitle.setText("수정 / 삭제하기");

        javax.swing.GroupLayout editFieldTitlePanelLayout = new javax.swing.GroupLayout(editFieldTitlePanel);
        editFieldTitlePanel.setLayout(editFieldTitlePanelLayout);
        editFieldTitlePanelLayout.setHorizontalGroup(
            editFieldTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editFieldTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        editFieldTitlePanelLayout.setVerticalGroup(
            editFieldTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editFieldTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        editProfileDataPanel.add(editFieldTitlePanel);
        editFieldTitlePanel.setBounds(10, 10, 240, 30);

        numberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberLabel.setText("학번");
        editProfileDataPanel.add(numberLabel);
        numberLabel.setBounds(10, 50, 240, 17);

        editProfileNumberField.setEditable(false);
        editProfileNumberField.setBackground(new java.awt.Color(255, 255, 255));
        editProfileNumberField.setForeground(new java.awt.Color(0, 0, 0));
        editProfileNumberField.setRound(10);
        editProfileDataPanel.add(editProfileNumberField);
        editProfileNumberField.setBounds(10, 70, 240, 27);

        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("이름");
        editProfileDataPanel.add(nameLabel);
        nameLabel.setBounds(10, 110, 240, 17);

        editProfileNameField.setBackground(new java.awt.Color(255, 255, 255));
        editProfileNameField.setForeground(new java.awt.Color(0, 0, 0));
        editProfileNameField.setRound(10);
        editProfileDataPanel.add(editProfileNameField);
        editProfileNameField.setBounds(10, 130, 240, 27);

        majorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        majorLabel.setText("학과");
        editProfileDataPanel.add(majorLabel);
        majorLabel.setBounds(10, 170, 240, 17);

        editProfileMajorField.setBackground(new java.awt.Color(255, 255, 255));
        editProfileMajorField.setForeground(new java.awt.Color(0, 0, 0));
        editProfileMajorField.setRound(10);
        editProfileDataPanel.add(editProfileMajorField);
        editProfileMajorField.setBounds(10, 190, 240, 27);

        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordLabel.setText("비밀번호");
        editProfileDataPanel.add(passwordLabel);
        passwordLabel.setBounds(10, 230, 240, 17);

        editProfilePasswordField.setBackground(new java.awt.Color(255, 255, 255));
        editProfilePasswordField.setForeground(new java.awt.Color(0, 0, 0));
        editProfilePasswordField.setRound(10);
        editProfileDataPanel.add(editProfilePasswordField);
        editProfilePasswordField.setBounds(10, 250, 240, 27);

        updateButton.setBackground(new java.awt.Color(0, 102, 255));
        updateButton.setText("변경사항 저장하기");
        updateButton.setBorderColor(new java.awt.Color(0, 102, 255));
        updateButton.setRoundBottomLeft(10);
        updateButton.setRoundBottomRight(10);
        updateButton.setRoundTopLeft(10);
        updateButton.setRoundTopRight(10);
        editProfileDataPanel.add(updateButton);
        updateButton.setBounds(10, 290, 240, 30);

        deleteButton.setBackground(new java.awt.Color(102, 102, 102));
        deleteButton.setText("삭제하기");
        deleteButton.setBorderColor(new java.awt.Color(102, 102, 102));
        deleteButton.setRoundBottomLeft(10);
        deleteButton.setRoundBottomRight(10);
        deleteButton.setRoundTopLeft(10);
        deleteButton.setRoundTopRight(10);
        editProfileDataPanel.add(deleteButton);
        deleteButton.setBounds(10, 330, 240, 30);

        add(editProfileDataPanel);
        editProfileDataPanel.setBounds(6, 170, 260, 370);

        userManagementPanel.setBackground(new java.awt.Color(255, 255, 255));
        userManagementPanel.setBorderColor(java.awt.Color.black);
        userManagementPanel.setRoundBottomLeft(15);
        userManagementPanel.setRoundBottomRight(15);
        userManagementPanel.setRoundTopLeft(15);
        userManagementPanel.setRoundTopRight(15);
        userManagementPanel.setLayout(null);

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "학번", "이름", "비밃번호", "학과"
            }
        ));
        jScrollPane1.setViewportView(userTable);

        userManagementPanel.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 800, 510);

        add(userManagementPanel);
        userManagementPanel.setBounds(272, 6, 820, 535);
    }// </editor-fold>//GEN-END:initComponents

    public void updateButtonListener(ActionListener listener) {
        updateButton.addActionListener(listener);
    }
    public void deleteButtonListener(ActionListener listener) {
        deleteButton.addActionListener(listener);
    }
    public void addTableInitListener(AncestorListener listener) {
        userTable.addAncestorListener(listener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private deu.view.custom.ButtonRound deleteButton;
    private javax.swing.JLabel editFieldTitle;
    private deu.view.custom.PanelRound editFieldTitlePanel;
    private deu.view.custom.PanelRound editProfileDataPanel;
    private deu.view.custom.TextFieldRound editProfileMajorField;
    private deu.view.custom.TextFieldRound editProfileNameField;
    private deu.view.custom.TextFieldRound editProfileNumberField;
    private deu.view.custom.TextFieldRound editProfilePasswordField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel majorLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JLabel passwordLabel;
    private deu.view.custom.LabelRound profileImageField;
    private deu.view.custom.TextFieldRound profileMajorField;
    private deu.view.custom.TextFieldRound profileNameField;
    private deu.view.custom.TextFieldRound profileNumberField;
    private deu.view.custom.PanelRound profilePanel;
    private deu.view.custom.ButtonRound updateButton;
    private deu.view.custom.PanelRound userManagementPanel;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
